{% set version = "1.0-1" %}

package:
  name: r-oce
  version: {{ version.replace("-", "_") }}

source:
  fn: oce_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/oce_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/oce/oce_{{ version }}.tar.gz
  sha256: f718288f83ff0dd6a296f446ac190378d9d828c6ab49d077bfd1ed7f6e4fc472

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:  # [not win32]
  build:  # [not win32]
    - r-base  # [not win32]
    - posix  # [win64]
    - m2w64-toolchain  # [win64]
    - gcc  # [not win]
    - r-gsw  # [not win32]
  run:  # [not win32]
    - r-base  # [not win32]
    - r-gsw  # [not win32]

test:
  commands:
    - R -e "library('oce')"  # [not win]
    - R -e \"library('oce')\"  # [win]

about:
  home: http://dankelley.github.com/oce/
  license: GPL-3.0
  summary: "Supports the analysis of Oceanographic data, including 'ADCP' measurements,
    measurements made with 'argo' floats, 'CTD' measurements, sectional data,
    sea-level time series, coastline and topographic data, etc. Provides specialized
    functions for calculating seawater properties such as potential temperature
    in either the 'UNESCO' or 'TEOS-10' equation of state. Produces graphical
    displays that conform to the conventions of the Oceanographic literature."

extra:
  recipe-maintainers:
    - ocefpaf
