appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: uJGjCgmLiBegH2EcEcxNE7oRKpbsQDwW7pvaG+kei/reOC4NJ9e0JGpFtqkuzpkafIjBLetN5/9iKDbv0v1LkWrbyBU9iJmVut2Zj0vtJJ0ieLVitZajvs9PwH+sMP50Ryj/Cu+BlvdycLWWTg3kacAIXdYWy0BVI0ZlEe3rdejmASMn24jo/2vTlVMLuPSNCQrtpulw6J1YZBaFe4IH//QuoSKosFg6yGCFJ3Vpi0D/UtO5gyOvgnDpVagLlcBm17CmrgOCxOJH12q5TIm+LyXfGGC5ALfrzgt6jnO/XygGPY7idtVy69LzKJvIFQYKfzUJX2iaEQ6hIogC7DDFS8odS9Kjd31oPAzs31mF8qfB+DZ+s464lnMwFH15bOWOSUaeGslyoZeLf5js9DVQySU1yCNY9tteGu52qxU8OBiuZSKzW5mmJ6Ze3C0a4MzcSD3LBHDFhsaG+ONekhZpVlYMcO2eGIdSIbAw4link8RchiNvHE7kwHi/UiqEV/nmwU0NQ1K7k0aVbkghbnHev3+ZwP+u92LrHiCpHYjDEMQAKeA/DvEINmx1pCVVKXrW2/usL5CvIpUqTeZAAhwt4jf5EEnX+1rCQMfmjYwkb+HriE8W7KNx0cOlwer+iu+VkAtTLbGZ+rfUNQDvNXaqRiAR2c8DK9qTv7OlynhSeIM=
conda_forge_output_validation: true
